# Iterateur

Julia possède un Type particulier fait à l'aide du ":"

In [34]:
a=1:5

1:5

In [35]:
typeof(a)

UnitRange{Int64} (constructor with 1 method)

In [36]:
b=0:0.5:2

0.0:0.5:2.0

In [37]:
typeof(b)

FloatRange{Float64} (constructor with 1 method)

# Tableau

On peut transformer l'itérateur précédent en tableau à l'aide de "[ ]"

In [38]:
aa=[a]

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [39]:
typeof(aa)

Array{Int64,1}

La réponse est de la forme **Array{Type,dim}** un tableau de **Type** à **dim** entrées (1 pour vecteur, 2 pour matrices ...)

Les crochets permettent la construction explicite de tableaux (ou leur concaténation)

In [40]:
A=[1 2 ; 3 4]

2x2 Array{Int64,2}:
 1  2
 3  4

On peut accéder à tout ou partie d'un tableau 

In [41]:
A[2,1]

3

In [42]:
A[2,:]

1x2 Array{Int64,2}:
 3  4

In [43]:
A[end,end]

4

A noter que l'on peut faire des tableau de tout type voir de les mélanger (Any)

In [90]:
a=["un";"deux"]

2-element Array{ASCIIString,1}:
 "un"  
 "deux"

In [92]:
b=["un"; 2 ; true]

3-element Array{Any,1}:
     "un"
    2    
 true    

## Algèbre linéaire

On retrouve beaucoup de fonctions usuelles de l'algèbre linéaire

In [44]:
size(A)

(2,2)

In [45]:
det(A)

-2.0

In [46]:
trace(A)

5

In [47]:
eigvals(A)

2-element Array{Float64,1}:
 -0.372281
  5.37228 

In [68]:
A=[1 2;3 4];b=[2 ; 3]; #résolution du système Ax=b
x=A\b 

2-element Array{Float64,1}:
 -1.0
  1.5

## Fonctions scientifiques et opérations

L'usage des fonction scientifiques se fait termes à termes sauf pour les fonctions matricielles

In [69]:
exp(A)

2x2 Array{Float64,2}:
  2.71828   7.38906
 20.0855   54.5982 

In [70]:
expm(A)

2x2 Array{Float64,2}:
  51.969   74.7366
 112.105  164.074 

De plus les tableaux possèdes des opérations de multiplication, division, puissance termes à termes

In [71]:
A^2 #Multiplication Matricielle

2x2 Array{Int64,2}:
  7  10
 15  22

In [72]:
A.^2 #Multiplication terme à terme

2x2 Array{Int64,2}:
 1   4
 9  16

In [73]:
A.//[2 3 ; 4 5] #Division terme à terme ici en fraction rationnelles

2x2 Array{Rational{Int64},2}:
 1//2  2//3
 3//4  4//5

## Constructeurs

Enfin il est possible de construire rapidement certaines matrices

In [74]:
a=linspace(0,1,3) #linspace(début,fin,nombre_éléments)

3-element Array{Float64,1}:
 0.0
 0.5
 1.0

In [75]:
B=[ones(3,2) zeros(3,2)] # concaténation de tableaux

3x4 Array{Float64,2}:
 1.0  1.0  0.0  0.0
 1.0  1.0  0.0  0.0
 1.0  1.0  0.0  0.0

In [76]:
C=eye(3,3)

3x3 Array{Float64,2}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

In [77]:
diagm(1:4)+diagm(5:7,1)

4x4 Array{Int64,2}:
 1  5  0  0
 0  2  6  0
 0  0  3  7
 0  0  0  4

In [78]:
diag(C)

3-element Array{Float64,1}:
 1.0
 1.0
 1.0