# Iterateur

Julia possède un Type particulier fait à l'aide du ":"

In [1]:
a=1:5

1:5

In [2]:
typeof(a)

UnitRange{Int64} (constructor with 1 method)

In [3]:
b=0:0.5:2

0.0:0.5:2.0

In [4]:
typeof(b)

FloatRange{Float64} (constructor with 1 method)

In [5]:
c=0:1//3:3

0//1:1//3:3//1

In [6]:
typeof(c)

StepRange{Rational{Int64},Rational{Int64}} (constructor with 1 method)

Ce type "formel" permet d'avoir une définition et une méthode associée sans stocker l'ensemble des valeurs. Attention celui-ci peut être vide :

In [7]:
d=1:0 # itérateur formel mais correspond à un ensemble vide de valeurs

1:0

# Tableau

On peut transformer l'itérateur précédent en tableau à l'aide de "[ ]"

In [8]:
aa=[a]

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [9]:
typeof(aa)

Array{Int64,1}

La réponse est de la forme **Array{Type,dim}** un tableau de **Type** à **dim** entrées (1 pour vecteur, 2 pour matrices ...)

A remarquer :
* l'indexation des tableaux commence à 1.
* un tableau à une entrée est vu comme un vecteur colonne par défaut.
* le crochet [ ] sert à extraire ou affecter une valeur ou un bloc de valeur

In [10]:
aa[1]

1

In [11]:
aa[end]

5

In [12]:
aa[end-2:end]=1; println(aa)

[1,2,1,1,1]


Les crochets permettent la construction explicite de tableaux (ou leur concaténation)

In [13]:
A=[1 2 ; 3 4]

2x2 Array{Int64,2}:
 1  2
 3  4

On peut accéder à tout ou partie d'un tableau 

In [14]:
A[2,1]

3

In [15]:
A[2,:]

1x2 Array{Int64,2}:
 3  4

In [16]:
A[end,end]

4

A noter que l'on peut faire des tableaux de tout type voir de les mélanger (Any)

In [17]:
a=["un";"deux"]

2-element Array{ASCIIString,1}:
 "un"  
 "deux"

In [18]:
b=["un"; 2 ; true]

3-element Array{Any,1}:
     "un"
    2    
 true    

Le crochet [ ] permet également la construction rapide de matrice ou tableau comme le montre l'exemple si dessous pour construire une matrice de VanderMonde

$$ V_{i,j}=x_i^{j-1}$$

In [19]:
x=0:0.2:1;
V=[ x[i]^(j-1) for i=1:6, j=1:6] # ligne et colonne

6x6 Array{Any,2}:
 1.0  0.0  0.0   0.0    0.0     0.0    
 1.0  0.2  0.04  0.008  0.0016  0.00032
 1.0  0.4  0.16  0.064  0.0256  0.01024
 1.0  0.6  0.36  0.216  0.1296  0.07776
 1.0  0.8  0.64  0.512  0.4096  0.32768
 1.0  1.0  1.0   1.0    1.0     1.0    

## Algèbre linéaire

On retrouve beaucoup de fonctions usuelles de l'algèbre linéaire

In [20]:
size(A)

(2,2)

In [21]:
det(A)

-2.0

In [22]:
trace(A)

5

In [23]:
eigvals(A)

2-element Array{Float64,1}:
 -0.372281
  5.37228 

In [24]:
A=[1 2;3 4];b=[2 ; 3]; #résolution du système Ax=b
x=A\b 

2-element Array{Float64,1}:
 -1.0
  1.5

## Fonctions scientifiques et opérations

L'usage des fonction scientifiques se fait termes à termes sauf pour les fonctions matricielles

In [25]:
exp(A)

2x2 Array{Float64,2}:
  2.71828   7.38906
 20.0855   54.5982 

In [26]:
expm(A)

2x2 Array{Float64,2}:
  51.969   74.7366
 112.105  164.074 

De plus les tableaux possèdes des opérations de multiplication, division, puissance termes à termes

In [27]:
A^2 #Multiplication Matricielle

2x2 Array{Int64,2}:
  7  10
 15  22

In [28]:
A.^2 #Multiplication terme à terme

2x2 Array{Int64,2}:
 1   4
 9  16

In [29]:
A.//[2 3 ; 4 5] #Division terme à terme ici en fraction rationnelles

2x2 Array{Rational{Int64},2}:
 1//2  2//3
 3//4  4//5

## Constructeurs

Enfin il est possible de construire rapidement certaines matrices

In [30]:
a=linspace(0,1,3) #linspace(début,fin,nombre_éléments)

3-element Array{Float64,1}:
 0.0
 0.5
 1.0

In [31]:
B=[ones(3,2) zeros(3,2)] # concaténation de tableaux

3x4 Array{Float64,2}:
 1.0  1.0  0.0  0.0
 1.0  1.0  0.0  0.0
 1.0  1.0  0.0  0.0

In [32]:
C=eye(3,3)

3x3 Array{Float64,2}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

In [33]:
diagm(1:4)+diagm(5:7,1)

4x4 Array{Int64,2}:
 1  5  0  0
 0  2  6  0
 0  0  3  7
 0  0  0  4

In [34]:
diag(C)

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

Et bien sur la définition d'un tableau à l'aide d'un itérateur 

In [35]:
D=[u*v for u=1:3, v=1:4]

3x4 Array{Int64,2}:
 1  2  3   4
 2  4  6   8
 3  6  9  12