# Tableaux et matrices

La définition de tableaux i.e. vecteurs, matrices, hypermatrices est un élément essentiel du Julia.

Julia ne possède qu'un seul type de tableau : **Array** on peut définir sont nombre d'entrées (1 entrée= 1 dimension ...) et sont contenu de façon assez générale (Un tableau peut contenir des matrices à chaque élément...

Une particularité est que les indices de tableaux commencent à 1, et l'acces aux éléments se fera à l'aide de '[' ’]' et non '(' ')' qui est réservé aux fonctions.

Avant de rentrer dans la construction et manipulation de tabelau regardons une autre classe 

# Iterateur

Julia possède un Type particulier fait à l'aide du ":"

In [1]:
a=1:5

1:5

In [2]:
typeof(a)

UnitRange{Int64}

In [3]:
b=0:0.5:2

0.0:0.5:2.0

In [4]:
typeof(b)

FloatRange{Float64}

In [5]:
c=0:1//3:3

0//1:1//3:3//1

In [6]:
typeof(c)

StepRange{Rational{Int64},Rational{Int64}}

Ce type "formel" permet d'avoir une définition et une méthode associée sans stocker l'ensemble des valeurs. Attention celui-ci peut être vide :

In [7]:
d=1:0 # itérateur formel mais correspond à un ensemble vide de valeurs

1:0

In [8]:
d=collect(d)

0-element Array{Int64,1}

# Tableau

On vient de voir que l'on peut transformer l'itérateur précédent en tableau à l'aide de la commande "collect"

In [9]:
a=1:5
aa=collect(a)

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [10]:
typeof(aa)

Array{Int64,1}

La réponse est de la forme **Array{Type,dim}** un tableau de **Type** à **dim** entrées (1 pour vecteur, 2 pour matrices ...)

A remarquer :
* l'indexation des tableaux commence à 1.
* un tableau à une entrée est vu comme un vecteur colonne par défaut.
* le crochet [ ] sert à extraire ou affecter une valeur ou un bloc de valeur. Attention le crochet [ ] sert également de "concatenateur" et constructeur de tableau (voir suite)
* Il est possible de faire des tableaux de n'importe quoi (fonction, tableau, ...).

In [11]:
aa[1]

1

In [12]:
aa[end] # pour accèder au dernier élément

5

In [13]:
aa[end-2:end]=1; println(aa)

[1,2,1,1,1]


Les crochets permettent la construction explicite de tableaux (ou leur concaténation)

In [14]:
A=[1 2 ; 3 4] # {espace} = séparateur de colonne {"," ou ";"} = séparateur de ligne

2x2 Array{Int64,2}:
 1  2
 3  4

In [15]:
AA=[A  A] # concaténation par block

2x4 Array{Int64,2}:
 1  2  1  2
 3  4  3  4

In [16]:
hcat(A,A) # commande équivalent à la précédente [A  A]

2x4 Array{Int64,2}:
 1  2  1  2
 3  4  3  4

In [17]:
AA=[A ; A]

4x2 Array{Int64,2}:
 1  2
 3  4
 1  2
 3  4

In [18]:
vcat(A,A) # commande équivalent à la précédente [A  ; A]

4x2 Array{Int64,2}:
 1  2
 3  4
 1  2
 3  4

On peut accéder à tout ou partie d'un tableau à l'aide de 2 indices

In [19]:
A[2,1]

3

In [20]:
A[2,:]

1x2 Array{Int64,2}:
 3  4

In [21]:
A[end,end]

4

In [22]:
B=[1,2,3,4]

4-element Array{Int64,1}:
 1
 2
 3
 4

In [23]:
B=[1;2;3;4]

4-element Array{Int64,1}:
 1
 2
 3
 4

A noter que l'on peut faire des tableaux de tout type voir de les mélanger (Any)

In [24]:
a=["un";"deux"]

2-element Array{ASCIIString,1}:
 "un"  
 "deux"

In [25]:
b=[1>2,true,false]

3-element Array{Bool,1}:
 false
  true
 false

In [26]:
c=["un"; 2 ; true]

3-element Array{Any,1}:
     "un"
    2    
 true    

Le crochet [ ] permet également la construction rapide de matrice ou tableau comme le montre l'exemple si dessous pour construire une matrice de VanderMonde

$$ V_{i,j}=x_i^{j-1}$$

In [27]:
x=0:0.2:1;
V=[ x[i]^(j-1) for i=1:6, j=1:6] # ligne et colonne

6x6 Array{Any,2}:
 1.0  0.0  0.0   0.0    0.0     0.0    
 1.0  0.2  0.04  0.008  0.0016  0.00032
 1.0  0.4  0.16  0.064  0.0256  0.01024
 1.0  0.6  0.36  0.216  0.1296  0.07776
 1.0  0.8  0.64  0.512  0.4096  0.32768
 1.0  1.0  1.0   1.0    1.0     1.0    

In [28]:
D=[ u*v for u=1:0.5:3, v=1:0.5:4]

5x7 Array{Float64,2}:
 1.0  1.5   2.0  2.5   3.0   3.5    4.0
 1.5  2.25  3.0  3.75  4.5   5.25   6.0
 2.0  3.0   4.0  5.0   6.0   7.0    8.0
 2.5  3.75  5.0  6.25  7.5   8.75  10.0
 3.0  4.5   6.0  7.5   9.0  10.5   12.0

On peux évidemment faire des tableaux à 3,4... entrèes.

## Manipulation de Tableau

### push!

Le fonction push permet d'ajouter à un tableau une valeur supplémentaire

In [29]:
a=[]
push!(a,1)     # => [1]
push!(a,2)     # => [1,2]
push!(a,4)     # => [1,2,4]
push!(a,6)     # => [1,2,4,6]

4-element Array{Any,1}:
 1
 2
 4
 6

### append!

Cette fonction permet de mettre bout à bout 2 tableaux

In [30]:
append!(a,a)

8-element Array{Any,1}:
 1
 2
 4
 6
 1
 2
 4
 6

## Algèbre linéaire

On retrouve beaucoup (toutes) de fonctions usuelles de l'algèbre linéaire

In [31]:
size(A)

(2,2)

In [32]:
det(A)

-2.0

In [33]:
trace(A)

5

In [34]:
eigvals(A)

2-element Array{Float64,1}:
 -0.372281
  5.37228 

In [35]:
A=[1 2;3 4];b=[2 ; 3]; #résolution du système Ax=b
x=A\b 

2-element Array{Float64,1}:
 -1.0
  1.5

## Fonctions scientifiques et opérations

L'usage des fonction scientifiques se fait termes à termes pour l'ensemble des valeurs du tableau (sauf pour les fonctions matricielles comme <code>expm</code>, <code>logm</code> ...). L'usage des opérations <code>+</code>,<code>-</code>,\*</code>,<code>^</code>,<code>/</code> et <code>\</code>(résolution) est disponible à condition de respecter les contraintes de dimension (multiplication matricielle par exemple). Sont ajouté des opérations termes à termes <code>.\*</code>,<code>.^</code>,<code>./</code> et <code>.\</code> toujours avec une contrainte de dimensions compatibles.

In [36]:
exp(A)

2x2 Array{Float64,2}:
  2.71828   7.38906
 20.0855   54.5982 

In [37]:
expm(A) # expoentielle matricielle

2x2 Array{Float64,2}:
  51.969   74.7366
 112.105  164.074 

De plus les tableaux possèdes des opérations de multiplication, division, puissance termes à termes

In [38]:
A^2 #Multiplication Matricielle

2x2 Array{Int64,2}:
  7  10
 15  22

In [39]:
A.^2 #Multiplication terme à terme

2x2 Array{Int64,2}:
 1   4
 9  16

In [40]:
A.//[2 3 ; 4 5] #Division terme à terme ici en fraction rationnelles

2x2 Array{Rational{Int64},2}:
 1//2  2//3
 3//4  4//5

## Constructeurs

Enfin il est possible de construire rapidement certaines matrices

In [41]:
a=linspace(0,1,3) #linspace(début,fin,nombre_éléments)

linspace(0.0,1.0,3)

In [42]:
A=ones(3)

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

In [43]:
B=randn(5) # loi normale centrée de variance 1

5-element Array{Float64,1}:
 -2.97776 
  1.49087 
 -0.271178
 -0.105431
  0.337501

In [44]:
B=[ones(3,2) zeros(3,2)] # concaténation de tableaux

3x4 Array{Float64,2}:
 1.0  1.0  0.0  0.0
 1.0  1.0  0.0  0.0
 1.0  1.0  0.0  0.0

In [55]:
B=[ones(3,2); zeros(3,2)] # , ou ; jouent le rôle de retour à la ligne

6x2 Array{Float64,2}:
 1.0  1.0
 1.0  1.0
 1.0  1.0
 0.0  0.0
 0.0  0.0
 0.0  0.0

In [46]:
C=eye(3,3)

3x3 Array{Float64,2}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

In [47]:
diagm(1:4)+diagm(5:7,1) # diagm à partir d'un vecteur cré une matrice

4x4 Array{Int64,2}:
 1  5  0  0
 0  2  6  0
 0  0  3  7
 0  0  0  4

In [48]:
diag(C) # extraction d'une diagonale

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

## type sparse

Julia possède un type sparse i.e. des matrices creuses, ces dernières ayant un comportement identique aux matrices elles ne diffèrent que dans leur définition (et leur stockage).

In [49]:
A=spzeros(3,3)

3x3 sparse matrix with 0 Float64 entries:

In [50]:
A=spdiagm(1:3)

3x3 sparse matrix with 3 Int64 entries:
	[1, 1]  =  1
	[2, 2]  =  2
	[3, 3]  =  3

In [51]:
A=A+spdiagm(1:2,1,3,3)

3x3 sparse matrix with 5 Int64 entries:
	[1, 1]  =  1
	[1, 2]  =  1
	[2, 2]  =  2
	[2, 3]  =  2
	[3, 3]  =  3

In [52]:
full(A) # pour passer à une matrice pleine

3x3 Array{Int64,2}:
 1  1  0
 0  2  2
 0  0  3

In [53]:
sparse(eye(4,4)) # pour rendre sparse une matrice "full"

4x4 sparse matrix with 4 Float64 entries:
	[1, 1]  =  1.0
	[2, 2]  =  1.0
	[3, 3]  =  1.0
	[4, 4]  =  1.0

In [54]:
det(A)

6.0